spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_system
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
  type-aliases-package: com.zc.mapper
  mapper-locations: classpath:mapper/*.xml
